spring:
  application:
    name: chat
  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CONVERSATION?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: qwer!0842
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  address: 0.0.0.0
  port: 8080

app:
  audit:
    zone: Asia/Seoul # UTC 또는 Asia/Seoul
    temporal-type: local # instant | offset | local
  upload:
    base-url: http://${HOST_IP:localhost}:8080/files

token:
  secret-key: "Yt@3kL#9zP!qR1uS^dM7vWxE@zB5hNpT"
  refresh-secret-key: "N6xZ!kM#p3QvR8@uC1LzBw$sFtR#yTq2"
  token-time: 25200 # seconds
  refresh-token-time: 756000 # seconds

security:
  restricted-paths:
    static-path:
      - /
    api-path:
    hx-api-path:
      - /hx/conversations/**

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none

logging:
  level:
    org.hibernate:
      orm.jdbc.bind: trace
      SQL: DEBUG
